// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZQQDjSC9WqD_SolyJtNUm4txX4Lkq0LE',
    appId: '1:745371036810:web:fb68e03d0c0c748e15d173',
    messagingSenderId: '745371036810',
    projectId: 'reddit-tutorial-e83c3',
    authDomain: 'reddit-tutorial-e83c3.firebaseapp.com',
    storageBucket: 'reddit-tutorial-e83c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNJYT_pBx8gYjFGI1XNgQoxs2V1Gj6vY',
    appId: '1:745371036810:android:8c1633328f89e59415d173',
    messagingSenderId: '745371036810',
    projectId: 'reddit-tutorial-e83c3',
    storageBucket: 'reddit-tutorial-e83c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1m5VUrVfdXv4a6-edY7OTN2pCarLWGRE',
    appId: '1:745371036810:ios:9bab9fd26d54240415d173',
    messagingSenderId: '745371036810',
    projectId: 'reddit-tutorial-e83c3',
    storageBucket: 'reddit-tutorial-e83c3.appspot.com',
    iosClientId: '745371036810-92eur2vvhb6u7djbp1rtkk21bevcu7an.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
